common:
	@sh components/common.sh
cart: common
	@sh components/cart.sh
catalogue: common
	@sh components/catalogue.sh
frontend: common
	@sh components/frontend.sh
mongodb: common
	@sh components/mongodb.sh

